flowchart TD
subgraph SA["API"]
Catalog["Catalogo<br>listar e buscar livros"]
Loan[" Emprestimo<br>empresa e devolve livros"]
Notification["Notificação<br>monitora e notifica prazo"]
end

Email["Email (Disparador de email)"]

Loan -->|consulta| Catalog
Loan -->|acionar| Notification
Notification -->| chama| Email
