flowchart LR

    V[Vendedor]
    A[Administrador]
    E[Operador de Estoque]

    WEB[Aplicação Web]
    API[API de Negócio]
    DB[(Banco de Dados)]

    V --> WEB
    A --> WEB
    E --> WEB

    WEB --> API
    API --> DB